@ip = http://localhost:5239
### get all tours
GET {{ip}}/api/tours

### post new tour
POST {{ip}}/api/tours
Content-Type: application/json

{"name":"XD","description":"fda","from":"fdsa","to":"fdsa", "transportType": "Bike",
"distance": 4000.3, "estimatedTime": 40.2, "fromCoordinate": {"lat": 48.192140901, "lng": 16.339604 },
"toCoordinate": {"lat": 48.20849, "lng": 16.37306}}

### Update Tour
PUT {{ip}}/api/tours/0
Content-Type: application/json

{"name":"bibibibi","description":"fda","from":"fdsa","to":"fdsa", "transportType": "Bike",
  "distance": 4000.3, "estimatedTime": 40.2}

### Delete Tour
DELETE {{ip}}/api/tours/0

########### GET TOUR LOGS
GET {{ip}}/api/tours/0/logs

############ ADD TOUR LOG
POST {{ip}}/api/tours/0/logs
Content-Type: application/json

{
  "tourId": 0,
  "date": "2026-04-03T14:30:00",
  "username": "Sercan",
  "difficulty": 5,
  "comment": "IM A ",
  "totalDistance": 12.5,
  "totalTime": 2.75,
  "rating": 4
}

############ UPDATE TOUR LOG
PUT {{ip}}/api/tours/0/logs/1
Content-Type: application/json

{
  "tourId": 0,
  "date": "2026-04-03T14:30:00",
  "username": "XD",
  "difficulty": 1,
  "totalDistance": 12432432.5,
  "totalTime": 233.75,
  "rating": 4
}

############ DELETE TOUR LOG
DELETE {{ip}}/api/tours/0/logs/0


