@ip = http://localhost:5239

GET {{ip}}/weatherforecast/
Accept: application/json

### get all tours
GET {{ip}}/api/tours

### post new tour
POST {{ip}}/api/tours
Content-Type: application/json

{"name":"tfdsafsda","description":"fda","from":"fdsa","to":"fdsa"}
