// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourPlanner.DAL;

#nullable disable

namespace TourPlanner.DAL.Migrations
{
    [DbContext(typeof(TourPlannerDBContext))]
    [Migration("20260628223731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourPlanner.DAL.Entities.Tour", b =>
                {
                    b.Property<int>("tour_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tour_id"));

                    b.Property<int?>("childFriendly")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<double>("distance")
                        .HasColumnType("double precision");

                    b.Property<int>("estimatedTime")
                        .HasColumnType("integer");

                    b.Property<int?>("popularity")
                        .HasColumnType("integer");

                    b.Property<string>("routeImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("startLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("targetLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tour_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("transportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("tour_id");

                    b.HasIndex("user_id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.TourLog", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("log_id"));

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<int>("difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("logDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<double>("totalDistance")
                        .HasColumnType("double precision");

                    b.Property<int>("totalTime")
                        .HasColumnType("integer");

                    b.Property<int>("tour_id")
                        .HasColumnType("integer");

                    b.HasKey("log_id");

                    b.HasIndex("tour_id");

                    b.ToTable("TourLogs");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("pw_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.Tour", b =>
                {
                    b.HasOne("TourPlanner.DAL.Entities.User", "User")
                        .WithMany("Tours")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.TourLog", b =>
                {
                    b.HasOne("TourPlanner.DAL.Entities.Tour", "Tour")
                        .WithMany("TourLogs")
                        .HasForeignKey("tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.Tour", b =>
                {
                    b.Navigation("TourLogs");
                });

            modelBuilder.Entity("TourPlanner.DAL.Entities.User", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
